# Usar una imagen base de Python
FROM python:3.10-slim-bullseye

# Copiamos el entrypoint antes para que tenga permisos
COPY entrypoint.sh /app/entrypoint.sh

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y wget tar && rm -rf /var/lib/apt/lists/*

# Damos permisos de ejecución al entrypoint
RUN chmod +x /app/entrypoint.sh

# Establecer directorio de trabajo
WORKDIR /app

# Ejecutar el entrypoint
RUN /app/entrypoint.sh

# Copiar requirements.txt
COPY requirements.txt .

# Instalar dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del proyecto
COPY . .

# Exponer puerto para la interfaz web
EXPOSE 8501

# Comando para ejecutar la aplicación
CMD ["streamlit", "run", "app.py", "--server.port=8501"]