
services:
  chess_trainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data

  notebooks:
    build:
      context: .
      dockerfile: dockerfile.notebooks
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
      - ./data:/notebooks/data

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=chess
      - POSTGRES_PASSWORD=chess_pass
      - POSTGRES_DB=chess_trainer_db
    ports:
      - "5432:5432"
    volumes:
      - chess_pgdata:/var/lib/postgresql/data

volumes:
  chess_pgdata:
