services:
  chess_trainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - chess_datasets:/app/src/data # Shared volume for generated datasets

  notebooks:
    build:
      context: .
      dockerfile: dockerfile.notebooks
    ports:
      - "8888:8888"
    volumes:
      - .:/chess_trainer  # Mount entire repository
      - chess_datasets:/chess_trainer/datasets  # Shared datasets volume
      - ./data:/chess_trainer/data  # Local data directory
    environment:
      - GIT_LFS_SKIP_SMUDGE=1  # Optional: skip LFS download on container start

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=chess
      - POSTGRES_PASSWORD=chess_pass
      - POSTGRES_DB=chess_trainer_db
    ports:
      - "5432:5432"
    volumes:
      - chess_pgdata:/var/lib/postgresql/data

volumes:
  chess_pgdata:
  chess_datasets: # New shared volume for Parquet datasets
