version: '3.8'

services:
  chess_trainer:
    build:
      context: .
    container_name: chess_trainer
    volumes:
      - .:/app
    ports:
      - "8501:8501"  # Streamlit, o ajustá si usás otra cosa
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://chess:chess_pass@postgres:5432/chess_trainer_db
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: chess_trainer_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: chess
      POSTGRES_PASSWORD: chess_pass
      POSTGRES_DB: chess_trainer_db
    ports:
      - "5432:5432"
    volumes:
      - chess_pgdata:/var/lib/postgresql/data

volumes:
  chess_pgdata:
