"""Generate 07_0_mental_model_lab.ipynb — test human 1600 mental model from PGN file."""

import json
from pathlib import Path

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Module 7.0 — Laboratorio modelo mental 1600 (rapid)\n",
            "\n",
            "**Fuentes:**\n",
            "- Diagramas HTML: [`07_cc_detection_algoritms/`](./07_cc_detection_algoritms/)\n",
            "- Informe de coherencia vs 07\\*: [`07_cc_human_mental_model_analysis.md`](./07_cc_human_mental_model_analysis.md)\n",
            "- Código: `analysis/mental_model/` (implementación *derivada* del HTML; la spec canónica humana sigue siendo el HTML)\n",
            "\n",
            "**Objetivo:** cargar un PGN desde archivo, elegir una jugada, y recorrer paso a paso:\n",
            "1. ¿Modo rápido o crítico?\n",
            "2. Disparadores E1–E11\n",
            "3. Plan de pensamiento (G, D, S)\n",
            "4. Mapeo a razones 07-base\n",
            "5. (Opcional) clasificar una candidata UCI + anti-blunder\n",
            "\n",
            "**No requiere** LLM ni Stockfish en este notebook.\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 0 — Configuración\n",
            "\n",
            "Edita `PGN_PATH` apuntando a tu partida `.pgn`. También puedes pegar PGN en `PGN_TEXT`.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "from pathlib import Path\n",
            "import io\n",
            "import json\n",
            "\n",
            "import chess\n",
            "import chess.pgn\n",
            "import pandas as pd\n",
            "\n",
            "from analysis.mental_model import assess_decision_point\n",
            "from analysis.mental_model.flow import assess_move_before_play\n",
            "from analysis.mental_model.candidate_taxonomy import classify_candidate_move, sort_candidates_by_priority\n",
            "from coaching.pgn_context import parse_pgn_sans\n",
            "\n",
            "COURSE_ROOT = Path('.').resolve()\n",
            "ARTIFACT_DIR = COURSE_ROOT / 'artifacts' / 'module07'\n",
            "ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "# --- Editar aquí ---\n",
            "PGN_PATH = COURSE_ROOT / 'sample_game.pgn'   # ruta a tu .pgn\n",
            "PGN_TEXT = ''   # o pegar PGN completo aquí (tiene prioridad si no está vacío)\n",
            "PLAYER_NAME = 'cmess1315'   # jugador a analizar (blancas o negras)\n",
            "PLAYER_ELO = 1600\n",
            "TIME_CONTROL = 'rapid'   # bullet | blitz | rapid | classical\n",
            "TARGET_PLY = None   # None = última jugada; o índice 0-based del ply a analizar\n",
            "CANDIDATE_UCI = None   # ej. 'e2e4' para probar anti-blunder; None = omitir\n",
            "\n",
            "print('Course root:', COURSE_ROOT)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 1 — Cargar PGN desde archivo\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "def load_pgn_text(path: Path, inline: str = '') -> str:\n",
            "    if inline and inline.strip():\n",
            "        return inline.strip()\n",
            "    if not path.is_file():\n",
            "        raise FileNotFoundError(\n",
            "            f'No se encontró {path}. Copia un .pgn ahí o usa PGN_TEXT.'\n",
            "        )\n",
            "    return path.read_text(encoding='utf-8', errors='replace')\n",
            "\n",
            "pgn_raw = load_pgn_text(PGN_PATH, PGN_TEXT)\n",
            "game = chess.pgn.read_game(io.StringIO(pgn_raw))\n",
            "if game is None:\n",
            "    raise ValueError('PGN inválido o vacío')\n",
            "\n",
            "headers = dict(game.headers)\n",
            "white = headers.get('White', '?')\n",
            "black = headers.get('Black', '?')\n",
            "result = headers.get('Result', '*')\n",
            "print(f'White: {white}  Black: {black}  Result: {result}')\n",
            "\n",
            "if PLAYER_NAME not in (white, black):\n",
            "    print(f'AVISO: {PLAYER_NAME!r} no está en la partida; se analiza el lado a mover igualmente.')\n",
            "\n",
            "sans = parse_pgn_sans(pgn_raw)\n",
            "print(f'Jugadas en la línea principal: {len(sans)}')\n",
            "print('Primeras plies:', ' '.join(sans[:8]), '...' if len(sans) > 8 else '')\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 2 — Reconstruir tablero hasta el ply elegido\n",
            "\n",
            "Tras la jugada del rival, **tú** tienes que decidir → evaluamos ese momento.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "board = game.board()\n",
            "ply = TARGET_PLY if TARGET_PLY is not None else max(0, len(sans) - 1)\n",
            "if ply >= len(sans):\n",
            "    raise ValueError(f'TARGET_PLY={ply} fuera de rango (max {len(sans)-1})')\n",
            "\n",
            "for i in range(ply + 1):\n",
            "    board.push(board.parse_san(sans[i]))\n",
            "\n",
            "move_no = ply // 2 + 1\n",
            "side = 'Blancas' if board.turn == chess.WHITE else 'Negras'\n",
            "last_san = sans[ply] if ply < len(sans) else '(fin)'\n",
            "print(f'Ply {ply} | jugada {move_no} | a mover: {side}')\n",
            "print(f'Última jugada aplicada: {last_san}')\n",
            "print('FEN:', board.fen())\n",
            "print(board)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 3 — (Opcional) Enlazar eval del curso SQLite\n",
            "\n",
            "Si tienes `course_data.sqlite` con features, intenta leer `score_diff` antes/después.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "score_before = None\n",
            "score_after = None\n",
            "\n",
            "try:\n",
            "    from data_access.features_repository import CourseFeaturesRepository\n",
            "    repo = CourseFeaturesRepository()\n",
            "    # Sin game_id del PGN hash no enlazamos filas automáticamente en este lab.\n",
            "    print('SQLite disponible. Para score_diff automático, pasa score_before/after manual abajo.')\n",
            "except Exception as exc:\n",
            "    print('SQLite no disponible:', exc)\n",
            "\n",
            "# Editar manualmente si conoces los centipeones desde Chess.com / engine\n",
            "score_before = None   # ej. 20\n",
            "score_after = None    # ej. -60\n",
            "print('score_before:', score_before, '| score_after:', score_after)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 4 — Evaluar: ¿modo rápido (C/C1) o crítico (E→F→G→…)?\n",
            "\n",
            "Corresponde al diagrama [`algoritmo_posiciones_criticas_ajedrez.html`](./07_cc_detection_algoritms/algoritmo_posiciones_criticas_ajedrez.html).\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "assessment = assess_decision_point(\n",
            "    board=board.copy(),\n",
            "    time_control=TIME_CONTROL,\n",
            "    player_elo=PLAYER_ELO,\n",
            "    score_diff_before=score_before,\n",
            "    score_diff_after=score_after,\n",
            ")\n",
            "\n",
            "print('=== MODO ===')\n",
            "print(assessment.mode.value.upper())\n",
            "print('Pausa sugerida (s):', assessment.pause_seconds)\n",
            "\n",
            "print('\\n=== DISPARADORES E1–E11 ===')\n",
            "if not assessment.triggers:\n",
            "    print('(ninguno — coherente con modo rápido C/C1)')\n",
            "for t in assessment.triggers:\n",
            "    print(f\"  {t.code.value} [{t.confidence:.2f}] {t.label_es}\")\n",
            "    for ev in t.evidence:\n",
            "        print(f'      - {ev}')\n",
            "\n",
            "print('\\n=== MAPEO 07-base (CriticalityReason) ===')\n",
            "print(assessment.mapped_07_reasons or ['(ninguno)'])\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 5 — Plan de pensamiento (pasos del HTML)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "plan_df = pd.DataFrame(\n",
            "    [\n",
            "        {'nodo': s.node_id, 'fase': s.phase, 'pregunta': s.prompt_es}\n",
            "        for s in assessment.thinking_plan\n",
            "    ]\n",
            ")\n",
            "plan_df\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 6 — Generar candidatas (D1–D5) desde jugadas legales\n",
            "\n",
            "En producción esto se alimentará con Stockfish MultiPV. Aquí clasificamos las legales con la heurística del HTML candidatas.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "position = board.copy()\n",
            "legal = list(position.legal_moves)\n",
            "ordered = sort_candidates_by_priority(position, legal[:12])  # limitar para display\n",
            "\n",
            "rows = []\n",
            "for move, cat in ordered[:8]:\n",
            "    rows.append({\n",
            "        'uci': move.uci(),\n",
            "        'san': position.san(move),\n",
            "        'categoria': cat.value,\n",
            "    })\n",
            "candidates_df = pd.DataFrame(rows)\n",
            "print('Top candidatas heurísticas (orden F: forzante → activa → sólida):')\n",
            "candidates_df\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 7 — Anti-blunder (S1–S4) sobre una candidata\n",
            "\n",
            "Edita `CANDIDATE_UCI` en Paso 0, o usa la primera de la tabla.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "uci = CANDIDATE_UCI or (candidates_df.iloc[0]['uci'] if len(candidates_df) else None)\n",
            "if uci is None:\n",
            "    print('Sin candidata para probar.')\n",
            "else:\n",
            "    move = chess.Move.from_uci(uci)\n",
            "    move_assessment = assess_move_before_play(\n",
            "        board.copy(), move,\n",
            "        time_control=TIME_CONTROL,\n",
            "        player_elo=PLAYER_ELO,\n",
            "        score_diff_before=score_before,\n",
            "        score_diff_after=score_after,\n",
            "    )\n",
            "    print('Candidata:', uci, '→', board.san(move) if move in board.legal_moves else '(ilegal)')\n",
            "    print('¿Pasa anti-blunder?', move_assessment.meta.get('move_safe'))\n",
            "    print('Checks fallidos:', move_assessment.meta.get('anti_blunder_failed', []))\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 8 — Recorrer toda la partida (resumen por ply del jugador)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "player_is_white = headers.get('White') == PLAYER_NAME\n",
            "if headers.get('Black') == PLAYER_NAME:\n",
            "    player_is_white = False\n",
            "\n",
            "summary_rows = []\n",
            "b = game.board()\n",
            "for p in range(len(sans)):\n",
            "    b.push(b.parse_san(sans[p]))\n",
            "    is_player_turn = (b.turn == chess.WHITE) == player_is_white\n",
            "    if not is_player_turn:\n",
            "        continue\n",
            "    a = assess_decision_point(board=b.copy(), time_control=TIME_CONTROL, player_elo=PLAYER_ELO)\n",
            "    summary_rows.append({\n",
            "        'ply': p,\n",
            "        'san_before': sans[p],\n",
            "        'mode': a.mode.value,\n",
            "        'triggers': ','.join(t.code.value for t in a.triggers) or '-',\n",
            "        'pause_s': a.pause_seconds,\n",
            "    })\n",
            "\n",
            "summary_df = pd.DataFrame(summary_rows)\n",
            "print(f'Plies del jugador {PLAYER_NAME}: {len(summary_df)}')\n",
            "print('Críticos:', (summary_df['mode'] == 'critical').sum())\n",
            "summary_df\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 9 — Exportar resultado JSON\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "export = {\n",
            "    'fen': assessment.meta.get('fen'),\n",
            "    'mode': assessment.mode.value,\n",
            "    'pause_seconds': assessment.pause_seconds,\n",
            "    'triggers': [\n",
            "        {'code': t.code.value, 'label': t.label_es, 'evidence': t.evidence}\n",
            "        for t in assessment.triggers\n",
            "    ],\n",
            "    'mapped_07_reasons': assessment.mapped_07_reasons,\n",
            "    'thinking_plan': [\n",
            "        {'node': s.node_id, 'phase': s.phase, 'prompt': s.prompt_es}\n",
            "        for s in assessment.thinking_plan\n",
            "    ],\n",
            "}\n",
            "out_path = ARTIFACT_DIR / 'mental_model_assessment.json'\n",
            "out_path.write_text(json.dumps(export, ensure_ascii=False, indent=2), encoding='utf-8')\n",
            "print('Guardado:', out_path)\n",
        ],
    },
]

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
    },
    "cells": cells,
}

out = Path(__file__).resolve().parent / "07_0_mental_model_lab.ipynb"
out.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"Wrote {out}")
