"""Generate 06_6_product_reset_human_validation.ipynb."""

import json
from pathlib import Path

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Module 6.6 — Product Reset & Human Validation\n",
            "\n",
            "Spec: `06_6_product_reset_human_validation.md`\n",
            "\n",
            "**Human in the loop:** revisa si el coaching de 6.5 es **útil y correcto**, no solo bien redactado.\n",
            "\n",
            "Prerrequisito: ejecutar **Module 6.5** Phase A (o tener `artifacts/module06_5/debug/phase_a/full_llm_payload.json`).\n",
            "\n",
            "Este notebook **no llama al LLM** por defecto.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "from pathlib import Path\n",
            "import json\n",
            "from datetime import datetime, timezone\n",
            "\n",
            "import pandas as pd\n",
            "\n",
            "from coaching.coaching_generate import generate_single_game_coaching\n",
            "from coaching.coaching_validation import validate_coaching_response\n",
            "from coaching.critical_move_contract import validate_critical_moves\n",
            "from coaching.deterministic_coaching import render_deterministic_coaching\n",
            "from coaching.game_analysis import DEFAULT_COURSE_PLAYER, summarize_game\n",
            "from coaching.human_brief import build_verbal_game_brief\n",
            "from coaching.pipeline import explain_player_games, prepare_player_game_analysis\n",
            "from coaching.prompt_builder import prepare_single_game_brief_for_llm\n",
            "from data_access.features_repository import CourseFeaturesRepository\n",
            "from dataset.feature_engineering import resolve_model_feature_columns\n",
            "from dataset.game_splits import split_by_game_id\n",
            "from explainability.human_pattern_models import load_human_pattern_model\n",
            "from explainability.shap_analysis import compute_global_shap_importance, explain_prediction\n",
            "from llm.settings import load_course_env\n",
            "\n",
            "load_course_env()\n",
            "pd.set_option('display.max_colwidth', 120)\n",
            "\n",
            "REPO_ROOT = Path('../..').resolve()\n",
            "COURSE_ROOT = Path('.').resolve()\n",
            "DATASET_PATH = REPO_ROOT / 'data' / 'datasets' / 'course_training_dataset.parquet'\n",
            "MODULE06_DIR = REPO_ROOT / 'artifacts' / 'module06'\n",
            "ARTIFACT_65 = COURSE_ROOT / 'artifacts' / 'module06_5'\n",
            "ARTIFACT_66 = COURSE_ROOT / 'artifacts' / 'module06_6'\n",
            "DEBUG_65 = ARTIFACT_65 / 'debug' / 'phase_a'\n",
            "ARTIFACT_66.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "PLAYER_NAME = DEFAULT_COURSE_PLAYER\n",
            "SPLIT_SEED = 42\n",
            "REVIEWER_ID = 'coach_1'  # change per session\n",
            "\n",
            "repo = CourseFeaturesRepository()\n",
            "model = load_human_pattern_model(MODULE06_DIR / 'human_model.joblib')\n",
            "course_df = pd.read_parquet(DATASET_PATH)\n",
            "human_columns = resolve_model_feature_columns(course_df, feature_set='human')\n",
            "_, val_df, _ = split_by_game_id(course_df, target_column='error_label', random_state=SPLIT_SEED)\n",
            "print('Player:', PLAYER_NAME)\n",
            "print('Artifact 6.6:', ARTIFACT_66)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 1 — Cargar caso de revisión (desde 6.5 o regenerar sin LLM)\n",
            "\n",
            "Prioridad: artefactos de debug de 6.5. Si no existen, se reconstruye el brief desde una partida del split validación.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "def _explainer_factory(sample):\n",
            "    _, _, explainer, _ = compute_global_shap_importance(model, sample)\n",
            "    return explainer\n",
            "\n",
            "payload_path = DEBUG_65 / 'full_llm_payload.json'\n",
            "llm_text_path = DEBUG_65 / 'gemini_response_valid.txt'\n",
            "if not llm_text_path.is_file():\n",
            "    llm_text_path = DEBUG_65 / 'gemini_response_rejected.txt'\n",
            "\n",
            "if payload_path.is_file():\n",
            "    llm_payload = json.loads(payload_path.read_text(encoding='utf-8'))\n",
            "    game_id = (llm_payload.get('game') or {}).get('opponent') or 'from_debug'\n",
            "    case_source = 'module06_5_debug'\n",
            "    print('Loaded payload from', payload_path)\n",
            "else:\n",
            "    single_game_ids, color_index = prepare_player_game_analysis(\n",
            "        repo, val_df, player_name=PLAYER_NAME, n_games=1, random_state=SPLIT_SEED,\n",
            "    )\n",
            "    game_id = single_game_ids[0]\n",
            "    player_moves, y_moves, X_moves, explanations, patterns, summaries = explain_player_games(\n",
            "        model, _explainer_factory, explain_prediction,\n",
            "        dataset=val_df[val_df['game_id'] == game_id],\n",
            "        full_split_df=val_df,\n",
            "        feature_columns=human_columns,\n",
            "        game_ids=single_game_ids,\n",
            "        player_name=PLAYER_NAME,\n",
            "        player_color_index=color_index,\n",
            "    )\n",
            "    brief = build_verbal_game_brief(\n",
            "        game_summary=summaries[0],\n",
            "        pattern_observations=patterns,\n",
            "        sample_labels=y_moves,\n",
            "        player_name=PLAYER_NAME,\n",
            "        player_moves=player_moves,\n",
            "        explanations=explanations,\n",
            "        feature_rows=X_moves,\n",
            "        repo=repo,\n",
            "        game_id=game_id,\n",
            "        player_color_index=color_index,\n",
            "    )\n",
            "    llm_payload = prepare_single_game_brief_for_llm(brief)\n",
            "    case_source = 'regenerated_no_llm'\n",
            "    print('Regenerated brief for game_id:', game_id)\n",
            "\n",
            "llm_report_text = llm_text_path.read_text(encoding='utf-8') if llm_text_path.is_file() else None\n",
            "deterministic_text = render_deterministic_coaching(\n",
            "    llm_payload.get('game') or {},\n",
            "    llm_payload.get('critical_moves') or [],\n",
            "    player=llm_payload.get('player'),\n",
            ")\n",
            "case_id = f\"{PLAYER_NAME}_{game_id if isinstance(game_id, str) else 'case'}\"\n",
            "print('case_id:', case_id, '| source:', case_source)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2 — Panel de evidencia (sin LLM)\n",
            "\n",
            "Separa **evidencia estructurada** (Python) de **narrativa** (LLM opcional).\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "print('=== lesson_clusters ===')\n",
            "for cluster in llm_payload.get('lesson_clusters') or []:\n",
            "    print('-', cluster.get('title'), '| evidence:', cluster.get('evidence_moves'))\n",
            "    print('  idea:', (cluster.get('idea') or '')[:200])\n",
            "\n",
            "print('\\n=== critical_moves (first 5) ===')\n",
            "for moment in (llm_payload.get('critical_moves') or [])[:5]:\n",
            "    print(\n",
            "        moment.get('move_number'),\n",
            "        moment.get('player_move'),\n",
            "        '|', moment.get('diagnosis_type'),\n",
            "        '|', moment.get('theme') or moment.get('pattern'),\n",
            "    )\n",
            "    print('  issue:', (moment.get('issue') or '')[:160])\n",
            "\n",
            "review_pack = {\n",
            "    'case_id': case_id,\n",
            "    'source': case_source,\n",
            "    'player': llm_payload.get('player'),\n",
            "    'game': llm_payload.get('game'),\n",
            "    'lesson_clusters': llm_payload.get('lesson_clusters'),\n",
            "    'critical_moves': llm_payload.get('critical_moves'),\n",
            "    'variants': {\n",
            "        'B_deterministic': deterministic_text,\n",
            "        'C_llm': llm_report_text,\n",
            "    },\n",
            "}\n",
            "pack_path = ARTIFACT_66 / f'review_pack_{case_id[:48]}.json'\n",
            "pack_path.write_text(json.dumps(review_pack, indent=2, ensure_ascii=False), encoding='utf-8')\n",
            "print('\\nSaved review pack:', pack_path)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 3 — Pre-checks automáticos\n",
            "\n",
            "Validación de contrato + formato V7 si hay texto LLM guardado.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "cm_validation = validate_critical_moves(llm_payload.get('critical_moves'))\n",
            "print('critical_moves contract:', 'OK' if cm_validation.ok else cm_validation.errors)\n",
            "if llm_report_text:\n",
            "    resp_val = validate_coaching_response(\n",
            "        llm_report_text,\n",
            "        llm_payload.get('critical_moves') or [],\n",
            "    )\n",
            "    print('LLM response validation:', 'OK' if resp_val.ok else resp_val.errors)\n",
            "    print('warnings:', resp_val.warnings)\n",
            "else:\n",
            "    print('No LLM report in debug — skip response validation (variant B only).')\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4 — Human in the loop\n",
            "\n",
            "Edita `coach_review` con tu criterio de entrenador. Escala sugerida: 0 = incorrecto, 1 = parcial, 2 = correcto y útil.\n",
            "\n",
            "Pregunta clave: ¿la **issue** y la **lección** son pedagógicamente verdaderas para este alumno?\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "coach_review = {\n",
            "    'reviewer_id': REVIEWER_ID,\n",
            "    'reviewed_at': datetime.now(timezone.utc).isoformat(),\n",
            "    'overall_useful': None,  # 0 | 1 | 2\n",
            "    'moments': [\n",
            "        {\n",
            "            'move_number': m.get('move_number'),\n",
            "            'correctness': None,\n",
            "            'relevance': None,\n",
            "            'priority': None,\n",
            "            'level_fit': None,\n",
            "            'actionability': None,\n",
            "            'preferred_diagnosis': '',\n",
            "            'preferred_training_action': '',\n",
            "            'comments': '',\n",
            "        }\n",
            "        for m in (llm_payload.get('critical_moves') or [])\n",
            "    ],\n",
            "    'lessons': [\n",
            "        {\n",
            "            'title': c.get('title'),\n",
            "            'correct': None,\n",
            "            'priority_correct': None,\n",
            "            'better_priority': '',\n",
            "            'coach_comment': '',\n",
            "        }\n",
            "        for c in (llm_payload.get('lesson_clusters') or [])\n",
            "    ],\n",
            "    'harmful_recommendation': False,\n",
            "    'abstain_would_be_better': False,\n",
            "}\n",
            "coach_review\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5 — Persistir validación\n",
            "\n",
            "Completa los campos `None` en la celda anterior antes de ejecutar.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "record = {\n",
            "    'case_id': case_id,\n",
            "    'source': case_source,\n",
            "    'system': review_pack,\n",
            "    'coach_review': coach_review,\n",
            "}\n",
            "jsonl_path = ARTIFACT_66 / 'validated_cases.jsonl'\n",
            "with jsonl_path.open('a', encoding='utf-8') as handle:\n",
            "    handle.write(json.dumps(record, ensure_ascii=False) + '\\n')\n",
            "print('Appended to', jsonl_path)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 6 — Resumen de fiabilidad (sesión)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "records = []\n",
            "jsonl_path = ARTIFACT_66 / 'validated_cases.jsonl'\n",
            "if jsonl_path.is_file():\n",
            "    records = [json.loads(line) for line in jsonl_path.read_text(encoding='utf-8').splitlines() if line.strip()]\n",
            "harmful = sum(1 for r in records if (r.get('coach_review') or {}).get('harmful_recommendation'))\n",
            "abstain = sum(1 for r in records if (r.get('coach_review') or {}).get('abstain_would_be_better'))\n",
            "summary = {\n",
            "    'cases_reviewed': len(records),\n",
            "    'harmful_flags': harmful,\n",
            "    'abstain_suggested': abstain,\n",
            "}\n",
            "(ARTIFACT_66 / 'reliability_summary.json').write_text(\n",
            "    json.dumps(summary, indent=2), encoding='utf-8',\n",
            ")\n",
            "summary\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 7 — Product reset memo\n",
            "\n",
            "Redacta en `artifacts/module06_6/product_reset_decision.md`:\n",
            "\n",
            "- ¿Continuar a RAG (Módulo 7) con el pipeline actual?\n",
            "- ¿Qué tipos de recomendación **limitar** o **abstener**?\n",
            "- ¿El MVP pasa a diagnóstico longitudinal (100+ partidas)?\n",
            "\n",
            "Criterio de salida: ver spec 6.6 y roadmap §6.6.10.\n",
        ],
    },
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

out = Path(__file__).resolve().parent / "06_6_product_reset_human_validation.ipynb"
out.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"Wrote {out}")
