"""Generate 07_0_mental_model_lab.ipynb — test human 1600 mental model from PGN file."""

import json
from pathlib import Path

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Module 7.0 — Laboratorio modelo mental 1600 (rapid)\n",
            "\n",
            "**Fuentes:**\n",
            "- Diagramas HTML: [`07_cc_detection_algoritms/`](./07_cc_detection_algoritms/)\n",
            "- Informe de coherencia vs 07\\*: [`07_cc_human_mental_model_analysis.md`](./07_cc_human_mental_model_analysis.md)\n",
            "- Código: `analysis/mental_model/` (implementación *derivada* del HTML; la spec canónica humana sigue siendo el HTML)\n",
            "\n",
            "**Objetivo:** cargar una partida (PGN o `game_id` de SQLite), elegir una jugada, y recorrer paso a paso:\n",
            "1. ¿Modo rápido o crítico?\n",
            "2. Disparadores E1–E11\n",
            "3. Plan de pensamiento (G, D, S)\n",
            "4. Mapeo a razones 07-base\n",
            "5. (Opcional) clasificar una candidata UCI + anti-blunder\n",
            "\n",
            "**No requiere** LLM ni Stockfish en este notebook.\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 0 — Configuración\n",
            "\n",
            "Tres formas de cargar la partida (F07-001):\n",
            "1. **`GAME_ID`** — partida ya en `course_data.sqlite` (recomendado si existe)\n",
            "2. **`PGN_TEXT`** — pegar PGN inline (tiene prioridad sobre archivo)\n",
            "3. **`PGN_PATH`** — archivo `.pgn` en `data/games/` (se crea si no existe)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "# F07-001 bootstrap v2 — does not use src/analysis\n",
            "from pathlib import Path\n",
            "import json\n",
            "import sys\n",
            "\n",
            "_cwd = Path.cwd().resolve()\n",
            "for _candidate in (_cwd, _cwd / 'docs' / 'ai_chess_coach_course'):\n",
            "    if (_candidate / 'mm_lab_imports.py').is_file():\n",
            "        sys.path.insert(0, str(_candidate))\n",
            "        break\n",
            "\n",
            "import chess\n",
            "import pandas as pd\n",
            "\n",
            "from mm_lab_imports import prepare_sys_path\n",
            "\n",
            "COURSE_ROOT = prepare_sys_path()\n",
            "from analysis.position_extractor import (\n",
            "    import_game_from_file,\n",
            "    import_game_from_pgn,\n",
            "    load_game_from_db,\n",
            ")\n",
            "from analysis.mental_model import assess_decision_point\n",
            "from analysis.mental_model.flow import assess_move_before_play\n",
            "from analysis.mental_model.candidate_taxonomy import sort_candidates_by_priority\n",
            "\n",
            "ARTIFACT_DIR = COURSE_ROOT / 'artifacts' / 'module07'\n",
            "ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)\n",
            "GAMES_DIR = COURSE_ROOT / 'data' / 'games'\n",
            "GAMES_DIR.mkdir(parents=True, exist_ok=True)\n",
            "print('Course analysis:', (COURSE_ROOT / 'analysis' / 'position_extractor.py'))\n",
            "\n",
            "# --- Editar aquí ---\n",
            "GAME_ID = ''   # ej. hash de partida en course_data.sqlite; vacío = usar PGN\n",
            "PGN_PATH = GAMES_DIR / 'sample_game.pgn'\n",
            "PGN_TEXT = ''   # pegar PGN completo (prioridad sobre PGN_PATH)\n",
            "PLAYER_NAME = 'cmess1315'\n",
            "PLAYER_ELO = 1600\n",
            "TIME_CONTROL = 'rapid'   # bullet | blitz | rapid | classical\n",
            "TARGET_PLY = None   # None = última jugada; índice 0-based\n",
            "CANDIDATE_UCI = None   # ej. 'e2e4'; None = primera candidata heurística\n",
            "\n",
            "print('Course root:', COURSE_ROOT)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 1 — Cargar partida (F07-001)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "if GAME_ID and str(GAME_ID).strip():\n",
            "    normalized_game = load_game_from_db(str(GAME_ID).strip())\n",
            "elif PGN_TEXT and str(PGN_TEXT).strip():\n",
            "    normalized_game = import_game_from_pgn(str(PGN_TEXT).strip())\n",
            "else:\n",
            "    normalized_game = import_game_from_file(PGN_PATH)\n",
            "\n",
            "headers = normalized_game.headers\n",
            "white = normalized_game.white_player or '?'\n",
            "black = normalized_game.black_player or '?'\n",
            "result = normalized_game.result or '*'\n",
            "sans = [p.san for p in normalized_game.plies]\n",
            "\n",
            "print(f'Fuente: {normalized_game.source} | game_id: {normalized_game.game_id}')\n",
            "print(f'White: {white}  Black: {black}  Result: {result}')\n",
            "print(f'Jugadas en la línea principal: {len(normalized_game.plies)}')\n",
            "print('Primeras plies:', ' '.join(sans[:8]), '...' if len(sans) > 8 else '')\n",
            "\n",
            "if PLAYER_NAME not in (white, black):\n",
            "    print(f'AVISO: {PLAYER_NAME!r} no está en la partida; se analiza el lado a mover igualmente.')\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 2 — Reconstruir tablero hasta el ply elegido\n",
            "\n",
            "Tras la jugada del rival, **tú** tienes que decidir → evaluamos ese momento.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "ply = TARGET_PLY if TARGET_PLY is not None else max(0, len(normalized_game.plies) - 1)\n",
            "if ply >= len(normalized_game.plies):\n",
            "    raise ValueError(f'TARGET_PLY={ply} fuera de rango (max {len(normalized_game.plies)-1})')\n",
            "\n",
            "record = normalized_game.plies[ply]\n",
            "board = chess.Board(record.fen_after)\n",
            "\n",
            "move_no = record.move_number\n",
            "side = 'Blancas' if board.turn == chess.WHITE else 'Negras'\n",
            "print(f'Ply {ply} | jugada {move_no} | a mover: {side}')\n",
            "print(f'Última jugada aplicada: {record.san}')\n",
            "print('FEN (posición a decidir):', board.fen())\n",
            "print(board)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 3 — Enlazar eval del curso SQLite\n",
            "\n",
            "Si la partida viene de la BD (`source=database`), lee `score_diff` del ply anterior y actual.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "score_before = None\n",
            "score_after = None\n",
            "\n",
            "if normalized_game.source == 'database' and ply > 0:\n",
            "    prev = normalized_game.plies[ply - 1]\n",
            "    curr = normalized_game.plies[ply]\n",
            "    score_before = prev.score_diff\n",
            "    score_after = curr.score_diff\n",
            "    print('score_diff desde features SQLite:')\n",
            "else:\n",
            "    print('Sin score_diff automático (PGN local). Edita manualmente si lo conoces.')\n",
            "\n",
            "# Override manual opcional\n",
            "# score_before = 20\n",
            "# score_after = -60\n",
            "print('score_before:', score_before, '| score_after:', score_after)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 4 — Evaluar: ¿modo rápido (C/C1) o crítico (E→F→G→…)?\n",
            "\n",
            "Corresponde al diagrama [`algoritmo_posiciones_criticas_ajedrez.html`](./07_cc_detection_algoritms/algoritmo_posiciones_criticas_ajedrez.html).\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "assessment = assess_decision_point(\n",
            "    board=board.copy(),\n",
            "    time_control=TIME_CONTROL,\n",
            "    player_elo=PLAYER_ELO,\n",
            "    score_diff_before=score_before,\n",
            "    score_diff_after=score_after,\n",
            ")\n",
            "\n",
            "print('=== MODO ===')\n",
            "print(assessment.mode.value.upper())\n",
            "print('Pausa sugerida (s):', assessment.pause_seconds)\n",
            "\n",
            "print('\\n=== DISPARADORES E1–E11 ===')\n",
            "if not assessment.triggers:\n",
            "    print('(ninguno — coherente con modo rápido C/C1)')\n",
            "for t in assessment.triggers:\n",
            "    print(f\"  {t.code.value} [{t.confidence:.2f}] {t.label_es}\")\n",
            "    for ev in t.evidence:\n",
            "        print(f'      - {ev}')\n",
            "\n",
            "print('\\n=== MAPEO 07-base (CriticalityReason) ===')\n",
            "print(assessment.mapped_07_reasons or ['(ninguno)'])\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 5 — Plan de pensamiento (pasos del HTML)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "plan_df = pd.DataFrame(\n",
            "    [\n",
            "        {'nodo': s.node_id, 'fase': s.phase, 'pregunta': s.prompt_es}\n",
            "        for s in assessment.thinking_plan\n",
            "    ]\n",
            ")\n",
            "plan_df\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 6 — Generar candidatas (D1–D5) desde jugadas legales\n",
            "\n",
            "En producción esto se alimentará con Stockfish MultiPV. Aquí clasificamos las legales con la heurística del HTML candidatas.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "position = board.copy()\n",
            "legal = list(position.legal_moves)\n",
            "ordered = sort_candidates_by_priority(position, legal[:12])  # limitar para display\n",
            "\n",
            "rows = []\n",
            "for move, cat in ordered[:8]:\n",
            "    rows.append({\n",
            "        'uci': move.uci(),\n",
            "        'san': position.san(move),\n",
            "        'categoria': cat.value,\n",
            "    })\n",
            "candidates_df = pd.DataFrame(rows)\n",
            "print('Top candidatas heurísticas (orden F: forzante → activa → sólida):')\n",
            "candidates_df\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 7 — Anti-blunder (S1–S4) sobre una candidata\n",
            "\n",
            "Edita `CANDIDATE_UCI` en Paso 0, o usa la primera de la tabla.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "uci = CANDIDATE_UCI or (candidates_df.iloc[0]['uci'] if len(candidates_df) else None)\n",
            "if uci is None:\n",
            "    print('Sin candidata para probar.')\n",
            "else:\n",
            "    move = chess.Move.from_uci(uci)\n",
            "    move_assessment = assess_move_before_play(\n",
            "        board.copy(), move,\n",
            "        time_control=TIME_CONTROL,\n",
            "        player_elo=PLAYER_ELO,\n",
            "        score_diff_before=score_before,\n",
            "        score_diff_after=score_after,\n",
            "    )\n",
            "    print('Candidata:', uci, '→', board.san(move) if move in board.legal_moves else '(ilegal)')\n",
            "    print('¿Pasa anti-blunder?', move_assessment.meta.get('move_safe'))\n",
            "    print('Checks fallidos:', move_assessment.meta.get('anti_blunder_failed', []))\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 8 — Recorrer toda la partida (resumen por ply del jugador)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "player_is_white = headers.get('White') == PLAYER_NAME\n",
            "if headers.get('Black') == PLAYER_NAME:\n",
            "    player_is_white = False\n",
            "\n",
            "summary_rows = []\n",
            "for record in normalized_game.plies:\n",
            "    b = chess.Board(record.fen_after)\n",
            "    is_player_turn = (b.turn == chess.WHITE) == player_is_white\n",
            "    if not is_player_turn:\n",
            "        continue\n",
            "    prev_score = normalized_game.plies[record.ply - 1].score_diff if record.ply > 0 else None\n",
            "    a = assess_decision_point(\n",
            "        board=b.copy(),\n",
            "        time_control=TIME_CONTROL,\n",
            "        player_elo=PLAYER_ELO,\n",
            "        score_diff_before=prev_score,\n",
            "        score_diff_after=record.score_diff,\n",
            "    )\n",
            "    summary_rows.append({\n",
            "        'ply': record.ply,\n",
            "        'san_before': record.san,\n",
            "        'mode': a.mode.value,\n",
            "        'triggers': ','.join(t.code.value for t in a.triggers) or '-',\n",
            "        'pause_s': a.pause_seconds,\n",
            "    })\n",
            "\n",
            "summary_df = pd.DataFrame(summary_rows)\n",
            "print(f'Plies del jugador {PLAYER_NAME}: {len(summary_df)}')\n",
            "print('Críticos:', (summary_df['mode'] == 'critical').sum())\n",
            "summary_df\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 9 — Exportar resultado JSON\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "export = {\n",
            "    'game_id': normalized_game.game_id,\n",
            "    'source': normalized_game.source,\n",
            "    'fen': assessment.meta.get('fen'),\n",
            "    'mode': assessment.mode.value,\n",
            "    'pause_seconds': assessment.pause_seconds,\n",
            "    'triggers': [\n",
            "        {'code': t.code.value, 'label': t.label_es, 'evidence': t.evidence}\n",
            "        for t in assessment.triggers\n",
            "    ],\n",
            "    'mapped_07_reasons': assessment.mapped_07_reasons,\n",
            "    'thinking_plan': [\n",
            "        {'node': s.node_id, 'phase': s.phase, 'prompt': s.prompt_es}\n",
            "        for s in assessment.thinking_plan\n",
            "    ],\n",
            "}\n",
            "out_path = ARTIFACT_DIR / 'mental_model_assessment.json'\n",
            "out_path.write_text(json.dumps(export, ensure_ascii=False, indent=2), encoding='utf-8')\n",
            "print('Guardado:', out_path)\n",
        ],
    },
]

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
    },
    "cells": cells,
}

out = Path(__file__).resolve().parent / "07_0_mental_model_lab.ipynb"
out.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"Wrote {out}")
