"""Generate 06_5_llm_coaching_recommendations.ipynb."""

import json
from pathlib import Path

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Module 6.5 — LLM Coaching Recommendations (Gemini 2.5 Flash)\n",
            "\n",
            "Spec: `06_5-ai_chess_coach_course_llm_coaching_recommendations.md`\n",
            "\n",
            "**Scope in this module**\n",
            "- **Phase A:** one **complete game** (every move by the coached player)\n",
            "- **Phase B:** a **player profile sample** (several complete games aggregated)\n",
            "- **Later modules:** hundreds/thousands of games → stable playing-style profile\n",
            "\n",
            "Pipeline:\n",
            "\n",
            "```text\n",
            "Complete game(s) → Human Pattern + SHAP per move → Pattern Engine → Context JSON → Gemini\n",
            "```\n",
            "\n",
            "Set `GEMINI_API_KEY` in the repo `.env` file. Optional: `pip install google-genai`\n",
            "\n",
            "**Cuota free tier:** gemini-2.5-flash ≈ 20 solicitudes/día. Ejecuta **una** celda LLM por sesión "
            "o espera al reinicio. Si ves 429, el notebook guarda el prompt y muestra aviso en español.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "from pathlib import Path\n",
            "\n",
            "import json\n",
            "import pandas as pd\n",
            "\n",
            "from coaching.context_builder import build_coaching_context, save_coaching_context\n",
            "from coaching.game_analysis import DEFAULT_COURSE_PLAYER, summarize_game\n",
            "from coaching.pipeline import explain_player_games, prepare_player_game_analysis\n",
            "from coaching.human_brief import build_verbal_game_brief\n",
            "from coaching.coaching_generate import generate_single_game_coaching\n",
            "from coaching.prompt_builder import (\n",
            "    build_coaching_prompt,\n",
            "    build_single_game_coaching_prompt,\n",
            "    prepare_single_game_brief_for_llm,\n",
            ")\n",
            "from data_access.features_repository import CourseFeaturesRepository\n",
            "from dataset.feature_engineering import resolve_model_feature_columns\n",
            "from dataset.game_splits import split_by_game_id\n",
            "from explainability.human_pattern_models import load_human_pattern_model\n",
            "from explainability.shap_analysis import compute_global_shap_importance, explain_prediction\n",
            "from llm import create_provider, generate_coaching_text, load_course_env, load_llm_settings\n",
            "\n",
            "loaded_env = load_course_env()\n",
            "if loaded_env:\n",
            "    print('Loaded env:', loaded_env)\n",
            "pd.set_option('display.max_columns', 80)\n",
            "\n",
            "REPO_ROOT = Path('../..').resolve()\n",
            "COURSE_ROOT = Path('.').resolve()\n",
            "DATASET_PATH = REPO_ROOT / 'data' / 'datasets' / 'course_training_dataset.parquet'\n",
            "MODULE06_DIR = REPO_ROOT / 'artifacts' / 'module06'\n",
            "ARTIFACT_DIR = COURSE_ROOT / 'artifacts' / 'module06_5'\n",
            "ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "PLAYER_NAME = DEFAULT_COURSE_PLAYER\n",
            "SINGLE_GAME_COUNT = 1\n",
            "PROFILE_GAME_COUNT = 8   # raise toward 50–500+ in production\n",
            "SPLIT_SEED = 42\n",
            "\n",
            "repo = CourseFeaturesRepository()\n",
            "model = load_human_pattern_model(MODULE06_DIR / 'human_model.joblib')\n",
            "course_df = pd.read_parquet(DATASET_PATH)\n",
            "human_columns = resolve_model_feature_columns(course_df, feature_set='human')\n",
            "_, val_df, _ = split_by_game_id(course_df, target_column='error_label', random_state=SPLIT_SEED)\n",
            "\n",
            "print('Coached player:', PLAYER_NAME)\n",
            "print('Validation games (all players):', val_df['game_id'].nunique())\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## LLM — modelo y cuota\n",
            "\n",
            "Ejecuta la celda siguiente para ver el modelo activo y enlaces a tus límites en AI Studio. "
            "En free tier suele haber pocas solicitudes/día por proyecto; activa **billing** en AI Studio para Tier 1.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "from IPython.display import HTML, display\n",
            "\n",
            "llm_settings = load_llm_settings()\n",
            "print('Provider :', llm_settings.provider)\n",
            "print('Model    :', llm_settings.model)\n",
            "print('API key  :', 'sí (GEMINI_API_KEY)' if llm_settings.has_api_key else 'no — modo dry-run local')\n",
            "print('Override : LLM_MODEL en .env para cambiar modelo (p. ej. gemini-2.5-flash-lite)')\n",
            "\n",
            "display(\n",
            "    HTML(\n",
            "        \"\"\"\n",
            "        <p><strong>Enlaces útiles (cuota y billing):</strong></p>\n",
            "        <ul>\n",
            "          <li><a href=\"https://aistudio.google.com/rate-limit\" target=\"_blank\">\n",
            "            AI Studio — Rate limits de tu proyecto</a></li>\n",
            "          <li><a href=\"https://ai.google.dev/gemini-api/docs/rate-limits\" target=\"_blank\">\n",
            "            Documentación — Rate limits Gemini API</a></li>\n",
            "          <li><a href=\"https://aistudio.google.com/apikey\" target=\"_blank\">\n",
            "            AI Studio — API keys y billing</a></li>\n",
            "        </ul>\n",
            "        <p><em>Free tier:</em> límite diario por proyecto y modelo (p. ej. ~20 req/día en\n",
            "        gemini-2.5-flash). Reinicio a medianoche PT. Ejecuta <strong>una</strong> celda LLM\n",
            "        por sesión (Fase A <em>o</em> Fase B).</p>\n",
            "        \"\"\"\n",
            "    )\n",
            ")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Phase A — One complete game\n",
            "\n",
            "We pick **one full game** from validation and analyze **every move** "
            "played by the coached player (`cmess1315`), not three random positions from different games.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "single_game_ids, color_index = prepare_player_game_analysis(\n",
            "    repo,\n",
            "    val_df,\n",
            "    player_name=PLAYER_NAME,\n",
            "    n_games=SINGLE_GAME_COUNT,\n",
            "    random_state=SPLIT_SEED,\n",
            ")\n",
            "single_summary = summarize_game(\n",
            "    val_df[val_df['game_id'] == single_game_ids[0]],\n",
            "    player_name=PLAYER_NAME,\n",
            "    player_color_index=color_index,\n",
            ")\n",
            "print('Game analyzed:', single_summary['game_id'])\n",
            "print('Opponent      :', single_summary['opponent'])\n",
            "print('Result        :', single_summary['result'])\n",
            "print('Opening       :', single_summary['opening'])\n",
            "print('Player moves  :', single_summary['player_moves_analyzed'])\n",
            "print('Move range    :', single_summary['move_number_range'])\n",
            "print('Errors        :', single_summary['error_breakdown'])\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "def _explainer_factory(sample):\n",
            "    _, _, explainer, _ = compute_global_shap_importance(model, sample)\n",
            "    return explainer\n",
            "\n",
            "player_moves, y_moves, X_moves, explanations, patterns, game_summaries = explain_player_games(\n",
            "    model,\n",
            "    _explainer_factory,\n",
            "    explain_prediction,\n",
            "    dataset=val_df,\n",
            "    full_split_df=val_df,\n",
            "    feature_columns=human_columns,\n",
            "    game_ids=single_game_ids,\n",
            "    player_name=PLAYER_NAME,\n",
            "    player_color_index=color_index,\n",
            ")\n",
            "print('Moves with SHAP in this game:', len(player_moves))\n",
            "print('Pattern hits:', len(patterns))\n",
            "explanations[0]\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Phase A — Brief + prompt (sin llamada LLM automática)\n",
            "\n",
            "Construye `critical_moves` con root-cause analysis, agrupa lecciones (V7) y guarda el prompt. "
            "**Gemini solo se invoca en la celda opcional más abajo.**\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "single_game_brief = build_verbal_game_brief(\n",
            "    game_summary=single_summary,\n",
            "    pattern_observations=patterns,\n",
            "    sample_labels=y_moves,\n",
            "    player_name=PLAYER_NAME,\n",
            "    player_moves=player_moves,\n",
            "    explanations=explanations,\n",
            "    feature_rows=X_moves,\n",
            "    repo=repo,\n",
            "    game_id=single_game_ids[0],\n",
            "    player_color_index=color_index,\n",
            ")\n",
            "print('Momentos críticos:', len(single_game_brief['critical_moves']))\n",
            "for moment in single_game_brief['critical_moves']:\n",
            "    print(moment.get('move'), '| root:', moment.get('root_cause'), '|', moment.get('pattern'))\n",
            "    if moment.get('tactical_line'):\n",
            "        print('  line:', moment.get('tactical_line'))\n",
            "    if moment.get('consequence_moves'):\n",
            "        print('  consecuencias:', moment.get('consequence_moves'))\n",
            "llm_payload = prepare_single_game_brief_for_llm(single_game_brief)\n",
            "print('Lecciones V7:', len(llm_payload.get('lesson_clusters', [])))\n",
            "for cluster in llm_payload.get('lesson_clusters', []):\n",
            "    print(' ', cluster.get('title'), '→', cluster.get('evidence_moves'))\n",
            "single_game_prompt = build_single_game_coaching_prompt(single_game_brief)\n",
            "single_prompt_path = ARTIFACT_DIR / 'single_game_prompt.txt'\n",
            "single_prompt_path.write_text(single_game_prompt, encoding='utf-8')\n",
            "print('Prompt guardado:', single_prompt_path)\n",
            "print('Longitud prompt:', len(single_game_prompt))\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Phase A — Invocar Gemini (manual, opcional)\n",
            "\n",
            "Ejecuta **solo esta celda** cuando quieras texto de coaching en vivo. "
            "Requiere `GEMINI_API_KEY`. No se llama a Gemini en el resto del notebook ni en pytest.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "# V7-lite: lecciones agrupadas + validación + debug + Gemini opcional.\n",
            "DEBUG_DIR = ARTIFACT_DIR / 'debug' / 'phase_a'\n",
            "INVOKE_GEMINI = False\n",
            "\n",
            "single_recommendation, quota_warning, coaching_meta = generate_single_game_coaching(\n",
            "    single_game_brief,\n",
            "    debug_dir=DEBUG_DIR,\n",
            "    invoke_llm=INVOKE_GEMINI,\n",
            ")\n",
            "single_game_path = ARTIFACT_DIR / 'single_game_recommendation.txt'\n",
            "single_game_path.write_text(single_recommendation, encoding='utf-8')\n",
            "print('Saved:', single_game_path)\n",
            "print('Debug dir:', coaching_meta.get('debug_dir'))\n",
            "print('Deterministic fallback:', coaching_meta.get('used_deterministic_fallback'))\n",
            "if not INVOKE_GEMINI:\n",
            "    print('Gemini no invocado. Pon INVOKE_GEMINI = True y re-ejecuta para llamar a la API.')\n",
            "if quota_warning:\n",
            "    print('AVISO:', quota_warning)\n",
            "if coaching_meta.get('response_validation'):\n",
            "    print('Response validation:', coaching_meta['response_validation'])\n",
            "print(single_recommendation[:2000])\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## Phase B — Player profile sample (multiple complete games)"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "profile_game_ids, profile_color_index = prepare_player_game_analysis(\n",
            "    repo,\n",
            "    val_df,\n",
            "    player_name=PLAYER_NAME,\n",
            "    n_games=PROFILE_GAME_COUNT,\n",
            "    random_state=SPLIT_SEED + 1,\n",
            ")\n",
            "\n",
            "profile_moves, profile_labels, _, _, profile_patterns, profile_summaries = explain_player_games(\n",
            "    model,\n",
            "    _explainer_factory,\n",
            "    explain_prediction,\n",
            "    dataset=val_df,\n",
            "    full_split_df=val_df,\n",
            "    feature_columns=human_columns,\n",
            "    game_ids=profile_game_ids,\n",
            "    player_name=PLAYER_NAME,\n",
            "    player_color_index=profile_color_index,\n",
            ")\n",
            "\n",
            "profile_table = pd.DataFrame(profile_summaries)\n",
            "print('Games in profile sample:', len(profile_summaries))\n",
            "print('Total player moves analyzed:', len(profile_moves))\n",
            "profile_table[['game_id', 'opponent', 'result', 'opening', 'player_moves_analyzed']]\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## Phase B — Context JSON + prompt (perfil, sin LLM automático)"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "context = build_coaching_context(\n",
            "    pattern_observations=profile_patterns,\n",
            "    sample_rows=profile_moves,\n",
            "    sample_labels=profile_labels,\n",
            "    player_name=PLAYER_NAME,\n",
            "    analysis_scope='player_profile_sample',\n",
            "    games_analyzed=profile_summaries,\n",
            ")\n",
            "context_path = ARTIFACT_DIR / 'sample_context.json'\n",
            "save_coaching_context(context, context_path)\n",
            "prompt = build_coaching_prompt(context)\n",
            "prompt_path = ARTIFACT_DIR / 'sample_prompt.txt'\n",
            "prompt_path.write_text(prompt, encoding='utf-8')\n",
            "print('Saved:', context_path)\n",
            "print('Prompt guardado:', prompt_path)\n",
            "json.dumps(context, indent=2)[:4000]\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Phase B — Invocar Gemini (manual, opcional)\n",
            "\n",
            "Ejecuta cuando quieras la recomendación de perfil. Una llamada por sesión en free tier.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "import os\n",
            "\n",
            "# Invocación manual: cambia a True solo cuando quieras gastar cuota Gemini.\n",
            "INVOKE_GEMINI = False\n",
            "\n",
            "if not INVOKE_GEMINI:\n",
            "    print('Gemini no invocado. Para llamar a la API, pon INVOKE_GEMINI = True y re-ejecuta esta celda.')\n",
            "else:\n",
            "    settings = load_llm_settings()\n",
            "    recommendation, quota_warning = generate_coaching_text(prompt, settings)\n",
            "    if quota_warning:\n",
            "        print('AVISO:', quota_warning)\n",
            "    recommendation_path = ARTIFACT_DIR / 'sample_recommendation.txt'\n",
            "    recommendation_path.write_text(recommendation, encoding='utf-8')\n",
            "    print('Saved:', recommendation_path)\n",
            "    print(recommendation[:2000])\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Pedagogy\n",
            "\n",
            "| Layer | What the student sees |\n",
            "|-------|----------------------|\n",
            "| **Game selection** | `game_id`, opponent, result, opening, move count |\n",
            "| **SHAP (Python only)** | Numeric evidence per move — never sent to Gemini |\n",
            "| **Pattern Engine** | Chess concepts aggregated across all moves in the sample |\n",
            "| **Root cause** | Python-only — agrupa síntomas bajo la jugada raíz |\n",
            "| **Phase A prompt** | `single_game_prompt.txt` — ejecutar Gemini manualmente |\n",
            "| **Phase B prompt** | `sample_prompt.txt` — ejecutar Gemini manualmente |\n",
            "\n",
            "**Next step (Modules 7–8):** scale `PROFILE_GAME_COUNT` to hundreds/thousands of games "
            "and persist a player pattern database for long-term style tracking.\n",
        ],
    },
]

notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python"},
    },
    "cells": cells,
}

output = Path(__file__).resolve().parent / "06_5_llm_coaching_recommendations.ipynb"
output.write_text(json.dumps(notebook, indent=1), encoding="utf-8")
print(f"Wrote {output}")
