"""Add unique constraint to features table

Revision ID: 21f1f768c296
Revises: 
Create Date: 2025-06-28 02:55:44.027180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f1f768c296'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_features')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_features',
    sa.Column('game_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('date_processed', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('game_id', name=op.f('processed_features_pkey'))
    )
    # ### end Alembic commands ###
