"""add proccess_features table

Revision ID: 65ec46878ca7
Revises: 21f1f768c296
Create Date: 2025-06-29 07:50:12.039324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ec46878ca7'
down_revision: Union[str, None] = '21f1f768c296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'processed_features',
        sa.Column('game_id', sa.String(), nullable=False),
        sa.Column('date_processed', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('game_id'),
        schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(
        'processed_features',
        schema='public'
    )
    # ### end Alembic commands ###
