"""Cambio de firma features.player_color

Revision ID: 66e04ee582df
Revises: 86729346b812
Create Date: 2025-06-13 22:08:54.568442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66e04ee582df'
down_revision: Union[str, None] = '86729346b812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('player_color', sa.Integer(), nullable=False),
    sa.Column('fen', sa.String(), nullable=True),
    sa.Column('move_san', sa.String(), nullable=True),
    sa.Column('move_uci', sa.String(), nullable=True),
    sa.Column('material_balance', sa.Float(), nullable=True),
    sa.Column('material_total', sa.Float(), nullable=True),
    sa.Column('num_pieces', sa.Integer(), nullable=True),
    sa.Column('branching_factor', sa.Integer(), nullable=True),
    sa.Column('self_mobility', sa.Integer(), nullable=True),
    sa.Column('opponent_mobility', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('has_castling_rights', sa.Integer(), nullable=True),
    sa.Column('move_number_global', sa.Integer(), nullable=True),
    sa.Column('is_repetition', sa.Integer(), nullable=True),
    sa.Column('is_low_mobility', sa.Integer(), nullable=True),
    sa.Column('is_center_controlled', sa.Integer(), nullable=True),
    sa.Column('is_pawn_endgame', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('score_diff', sa.Float(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('white_player', sa.String(), nullable=True),
    sa.Column('black_player', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('num_moves', sa.Integer(), nullable=True),
    sa.Column('is_stockfish_test', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('game_id', 'move_number', 'player_color'),
    schema='public'
    )
    op.drop_table('processed_features')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_features',
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_processed', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('game_id', name=op.f('processed_features_pkey'))
    )
    op.drop_table('features', schema='public')
    # ### end Alembic commands ###
