"""base schema snapshot

Revision ID: 8d489dbc7009
Revises: 
Create Date: 2025-06-14 08:50:13.903839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d489dbc7009'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_features',
                    sa.Column('game_id', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('date_processed', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'game_id', name=op.f('processed_features_pkey'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_features')
    op.add_column('features', sa.Column(
        'error_label', sa.String(), nullable=True))
    # ### end Alembic commands ###
