"""new table chapters

Revision ID: b7949ebb0699
Revises: 8d489dbc7009
Create Date: 2025-06-14 17:25:51.529409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7949ebb0699'
down_revision: Union[str, None] = '8d489dbc7009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
   # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'chapters',
        sa.Column('id', sa.Integer(), primary_key=True,
                  index=True, nullable=False),
        sa.Column('study_id', sa.String(), index=True, nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('pgn', sa.String(), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapters')
    # ### end Alembic commands ###
