"""add processed_features table

Revision ID: e48432060ba0
Revises: 48668c78a590
Create Date: 2025-06-18 15:36:24.724385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e48432060ba0'
down_revision: Union[str, None] = '48668c78a590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'processed_features',
        sa.Column('game_id', sa.String(length=64), nullable=False),
        sa.Column('date_processed', sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint('game_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_features')
    # ### end Alembic commands ###
